/* import { ingredient } from "./Ingredient";

export const INGREDIENTS : ingredient[]=[
    { id: 1, name: 'tomates', image:"https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn",type:'Légumes'},
    { id: 1, name: 'Tomate', image: "https://www.auchandirect.fr/backend/media/products_images/0N_57324.jpg", type: 'Légumes' },
    { id: 2, name: 'Courgette', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Légumes' },
    { id: 3, name: 'Carotte', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Légumes' },
    { id: 4, name: 'Poivrons', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Légumes' },
    { id: 5, name: 'Aubergine', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Légumes' },
    { id: 6, name: 'Citrouille', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Légumes' },
    { id: 7, name: 'Pomme de terre', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Légumes' },
    { id: 8, name: 'Patate douce', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Légumes' },
    { id: 9, name: 'Betrave', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Légumes' },
    { id: 10, name: 'Haricot vert', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Légumes' },
    { id: 11, name: 'Mangue', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Fruits' },
    { id: 12, name: 'Pomme', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Fruits' },
    { id: 13, name: 'Cerise', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Fruits' },
    { id: 14, name: 'Kiwi', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Fruits' },
    { id: 15, name: 'Banane', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Fruits' },
    { id: 16, name: 'Ananas', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Fruits' },
    { id: 17, name: 'Citron', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Fruits' },
    { id: 18, name: 'Noix de coco', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Fruits' },
    { id: 19, name: 'Fruit de la passion', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Fruits' },
    { id: 20, name: 'Poulet', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 21, name: 'Canard', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id:22, name: 'Lapin', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 23, name: 'Veau', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 24, name: 'Mouton', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 25, name: 'Porc', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 26, name: 'Dinde', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 27, name: 'Crevette', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 28, name: 'Boeuf', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 29, name: 'Cabillaud', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 30, name: 'Sardine', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 31, name: 'merlan', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Viandes/poissons' },
    { id: 32, name: 'Pain', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Céreales' },
    { id: 33, name: 'Biscotte', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Céreales' },
    { id: 34, name: 'Pattes', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Céreales' },
    { id: 35, name: 'Riz', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Céreales' },
    { id: 36, name: 'Pois chiche', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'Céreales' },
    { id: 37, name: 'Créme fraiche', image: "https://princedebretagne.com/sites/default/files/styles/vegetable_detail_thumbnail/public/vegetable-main-picture/tomates-saveurs-antans.png?itok=ygX16fNn", type: 'ProduitLaitier' }


] */